globs:
  - "README.md"
  - "CONTRIBUTING.md"
  - "usecases/**/*.md"

config:
  MD009: false
  MD012: false
  MD013: false
  MD022: false
  MD025: false
  MD029: false
  MD030: false
  MD031: false
  MD032: false
  MD033: false
  MD040: false
  MD041: false
  MD047: false
